import Head from 'next/head'
import Image from 'next/image'
import Icon from '@mdi/react'
import { mdiArrowDownThin, mdiGithub } from '@mdi/js'
import image1 from '../public/images/image1.png'
import logo from '../public/images/logo.svg'
import styles from '../styles/Home.module.scss'
import {Coins} from '../components/Coins/Coins'
import { ProductsList } from '../components/ProductsList/ProducstList'
import Walkthrough from '../components/Walkthrough/Walkthrough'
import Filters from '../components/Filters/Filters'
import { Link } from 'react-scroll';

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href={logo} />
      </Head>

      <nav className={styles.nav}>
        <div className={styles.logo}>
          <Image src={logo} alt="logo" />
        </div>
        <Coins />
      </nav>
      <div className={styles.landing}>
        <div className={styles.title}>
          <span>EXPLORE THE</span>
          <h1 className={styles.mainTitle}><span>TECH</span> ZONE</h1>
          <p>Here you’ll be able to exchange all of your hard-earned Aeropoints and exchange them for cool tech.</p>
          <Link activeClass="active" to="container" spy={true} smooth={true} offset={50} duration={500} className={styles.buttonPrimary}> 
            <span>VIEW ALL PRODUCTS</span>
            <Icon className={styles.icon} path={mdiArrowDownThin} />
          </Link>
        </div>
        <div >
          <Image className={styles.image} src={image1} alt="banner" height={795} width={897} />
          <div className={styles.imageBG} />
        </div>
        <div className={styles.landingBG}/>
      </div>
      <Walkthrough />

      <main name='container' className={styles.main}>
        <div>
          <h2><span>TECH</span> PRODUCTS</h2>
        </div>
        <Filters />
        <div>
          <ProductsList  />
        </div>
        {/* <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Next.js!</a>
        </h1>
          <div className={styles.logo}></div>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <div className={styles.grid}>
          <a href="https://nextjs.org/docs" className={styles.card}>
            <h2>Documentation &rarr;</h2>
            <p>Find in-depth information about Next.js features and API.</p>
          </a>

          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>

          <a
            href="https://github.com/vercel/next.js/tree/canary/examples"
            className={styles.card}
          >
            <h2>Examples &rarr;</h2>
            <p>Discover and deploy boilerplate example Next.js projects.</p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
          >
            <h2>Deploy &rarr;</h2>
            <p>
              Instantly deploy your Next.js site to a public URL with Vercel.
            </p>
          </a>
        </div> */}
      </main>

      <footer className={styles.footer}>
        <a
          href="#"
          target="_blank"
          rel="noopener noreferrer"
        >
         <Icon color="#8FA3BF" size={1} path={mdiGithub} /> 
         <span>View this repository </span>
        </a>
      </footer>
    </div>
  )
}
